"""
conftest.py — Auto-generated by qa-agent
Session-scoped fixtures for stateful CREATE → READ → DELETE test chains.
DO NOT EDIT MANUALLY — regenerated by: python cli.py --spec <spec> --generate
"""

import logging

import pytest
import requests

BASE_URL = "https://restful-booker.herokuapp.com"

logger = logging.getLogger(__name__)


@pytest.fixture(scope="session")
def created_booking():
    """
    Creates a booking resource and yields its ID.
    Cleans up after all tests in the session complete.
    """
    response = requests.post(
        f"{BASE_URL}/booking",
        json={'firstname': 'Jim', 'lastname': 'Brown', 'totalprice': 111, 'depositpaid': True, 'bookingdates': {'checkin': '2024-01-01', 'checkout': '2024-01-10'}, 'additionalneeds': 'Breakfast'}
    )
    assert response.status_code == 200, (
        f"Failed to create booking: "
        f"{response.status_code} {response.text}"
    )
    created_booking = response.json()["bookingid"]
    logger.info(f"Created booking with ID: {created_booking}")
    yield created_booking
    # Teardown — always runs even if tests fail
    requests.delete(f"{BASE_URL}/booking/{created_booking}")
    logger.info(f"Cleaned up booking ID: {created_booking}")

