"""
conftest_generator.py
Generates a pytest conftest.py with session-scoped fixtures for
stateful CREATE → READ → DELETE test chains.

Generic — works for any REST API.
"""

from __future__ import annotations

import json
from pathlib import Path

from agent.dependency_resolver import ResourceChain, detect_chains, _infer_id_field
from agent.logger import get_logger

logger = get_logger("conftest_generator", "qa_agent.log")


def _build_fixture_code(chain: ResourceChain) -> str:
    """
    Build a single pytest fixture for a resource chain.

    Example output:
        @pytest.fixture(scope="session")
        def created_booking():
            response = requests.post(f"{BASE_URL}/booking", json={...})
            assert response.status_code == 200
            booking_id = response.json()["bookingid"]
            yield booking_id
            requests.delete(f"{BASE_URL}/booking/{booking_id}")
    """
    creator = chain.creator
    if not creator:
        return ""

    base_url = creator.get("base_url", "")
    path = creator.get("path", "")
    valid_response = creator.get("valid_response") or {}
    response_body = valid_response.get("body")
    valid_status = valid_response.get("status_code", 200)

    # Infer ID field from real response
    id_field = _infer_id_field(response_body, chain.resource_name)

    # Handle nested ID like "booking.id"
    if "." in id_field:
        parent, child = id_field.split(".", 1)
        id_extraction = f'response.json()["{parent}"]["{child}"]'
    else:
        id_extraction = f'response.json()["{id_field}"]'

    # Build example payload from valid_response or spec
    from agent.api_prober import _extract_example_payload
    payload = {}
    if creator.get("request_body"):
        schema = creator["request_body"].get("schema", {})
        payload = _extract_example_payload(schema) or {}

    # Build cleanup code
    cleanup_lines = []
    for deleter in chain.deleters:
        del_path = deleter.get("path", "")
        # Replace path param with fixture variable
        import re
        del_path_rendered = re.sub(r"\{[^}]+\}", f"{{{chain.fixture_name}}}", del_path)
        cleanup_lines.append(
            f'    requests.delete(f"{{BASE_URL}}{del_path_rendered}")'
        )

    cleanup_code = "\n".join(cleanup_lines) if cleanup_lines else (
        f"    # No DELETE endpoint detected — manual cleanup may be needed"
    )

    return f'''
@pytest.fixture(scope="session")
def {chain.fixture_name}():
    """
    Creates a {chain.resource_name} resource and yields its ID.
    Cleans up after all tests in the session complete.
    """
    response = requests.post(
        f"{{BASE_URL}}{path}",
        json={repr(payload)}
    )
    assert response.status_code == {valid_status}, (
        f"Failed to create {chain.resource_name}: "
        f"{{response.status_code}} {{response.text}}"
    )
    {chain.fixture_name} = {id_extraction}
    logger.info(f"Created {chain.resource_name} with ID: {{{chain.fixture_name}}}")
    yield {chain.fixture_name}
    # Teardown — always runs even if tests fail
{cleanup_code}
    logger.info(f"Cleaned up {chain.resource_name} ID: {{{chain.fixture_name}}}")
'''


def generate_conftest(
    endpoints: list[dict],
    output_dir: str = "generated_tests",
    base_url: str = "",
) -> Path | None:
    """
    Detect chains and generate conftest.py with session-scoped fixtures.
    Returns the path to the generated file, or None if no chains detected.
    """
    chains = detect_chains(endpoints)

    if not chains:
        logger.info("No resource chains detected — skipping conftest.py generation")
        return None

    logger.info(f"Generating conftest.py for {len(chains)} chain(s)")

    fixtures = []
    for chain in chains:
        fixture_code = _build_fixture_code(chain)
        if fixture_code:
            fixtures.append(fixture_code)

    if not fixtures:
        return None

    # Build conftest.py content
    content = f'''"""
conftest.py — Auto-generated by qa-agent
Session-scoped fixtures for stateful CREATE → READ → DELETE test chains.
DO NOT EDIT MANUALLY — regenerated by: python cli.py --spec <spec> --generate
"""

import logging

import pytest
import requests

BASE_URL = "{base_url}"

logger = logging.getLogger(__name__)

{"".join(fixtures)}
'''

    out = Path(output_dir)
    out.mkdir(exist_ok=True)
    conftest_path = out / "conftest.py"
    conftest_path.write_text(content, encoding="utf-8")
    logger.info(f"Generated conftest.py → {conftest_path}")
    return conftest_path